TASK: few_shot
NUM_GPUS: 1
FEW_SHOT:
  N_WAY: 5
  K_SHOT: 1  
  TRAIN_QUERY_PER_CLASS: 6
  TEST_QUERY_PER_CLASS: 1
  TRAIN_EPISODES: 200
  TEST_EPISODES: 10000
  PATCH_TOKENS_AGG: spatial
  DIST_NORM: none
  TRAIN_OG_EPISODES: True

POINT_INFO:
  PT_FIX_SAMPLING_TRAIN: True
  PT_FIX_SAMPLING_TEST: True
  USE_PT_QUERY_MASK: True
  SAMPLING_TYPE: random
  NUM_POINTS_TO_SAMPLE: 256
  GRID_SIZE: 16

TRAIN:
  ENABLE: True
  DATASET: HMDB51
  BATCH_SIZE: 32
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  MIXED_PRECISION: True
DATA:
  REVERSE_INPUT_CHANNEL: True
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: torchvision
  NUM_FRAMES: 8
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  INV_UNIFORM_SAMPLE: True
  RANDOM_FLIP: False
AUG:
  NUM_SAMPLE: 1
  ENABLE: False
  DIFFERENT_AUG_PER_FRAME: True
  COLOR_JITTER: 0.0
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.0
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
SOLVER:
  BASE_LR: 0.0001
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01]
  STEPS: [0, 20, 40]
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.5
  WARMUP_EPOCHS: 5
  OPTIMIZING_METHOD: adamw
  TEMPRATURE: 1.0
  WARMUP_START_LR: 1e-06
MODEL:
  NUM_CLASSES: 51
  MODEL_NAME: Pointformer
  LOSS_FUNC: label_smoothing_cross_entropy
  VIT_TYPE: None
  RESNET_TYPE: None
TEST:
  ENABLE: True
  DATASET: HMDB51
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True





